<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now()->toDateTimeString();

        // Ambil publisher/major/origin yang sudah di-seed sebelumnya
        $pub = DB::table('publishers')->first();
        $pub2 = DB::table('publishers')->skip(1)->first();
        $mjr = DB::table('book_majors')->first();
        $mjr2 = DB::table('book_majors')->skip(1)->first();
        $orgn = DB::table('book_origins')->first();
        $orgn2 = DB::table('book_origins')->skip(1)->first();

        DB::table('books')->insert([
            [
                'bk_isbn' => null,
                'bk_title' => 'Pendidikan Agama Islam dan Budi Pekerti SMK Kelas X',
                'bk_description' => null,
                'bk_page' => 19,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '297',
                'bk_edition_volume' => null,
                'bk_published_year' => '2022',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Pendidikan Agama Islam dan Budi Pekerti SMK Kelas XI',
                'bk_description' => null,
                'bk_page' => 31,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '297',
                'bk_edition_volume' => null,
                'bk_published_year' => '2022',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Pendidikan Agama Islam dan Budi Pekerti SMK Kelas XII',
                'bk_description' => null,
                'bk_page' => 27,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '297',
                'bk_edition_volume' => null,
                'bk_published_year' => '2022',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Bahasa Indonesia SMK/MAK Kelas X',
                'bk_description' => null,
                'bk_page' => 25,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '499',
                'bk_edition_volume' => null,
                'bk_published_year' => '2021',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Bahasa Indonesia SMK/MAK Kelas XI',
                'bk_description' => null,
                'bk_page' => 38,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '499',
                'bk_edition_volume' => null,
                'bk_published_year' => '2021',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Bahasa Indonesia SMK/MAK Kelas XII',
                'bk_description' => null,
                'bk_page' => 27,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '499',
                'bk_edition_volume' => null,
                'bk_published_year' => '2023',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Pendidikan Pancasila SMK/MAK Kelas X',
                'bk_description' => null,
                'bk_page' => 28,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '323',
                'bk_edition_volume' => null,
                'bk_published_year' => '2021',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Pendidikan Pancasila SMK/MAK Kelas XI',
                'bk_description' => null,
                'bk_page' => 19,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '323',
                'bk_edition_volume' => null,
                'bk_published_year' => '2022',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Pendidikan Pancasila SMK/MAK Kelas XII',
                'bk_description' => null,
                'bk_page' => 20,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '323',
                'bk_edition_volume' => null,
                'bk_published_year' => '2024',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Splash Smart Path to Learning English SMK/MAK Grade X',
                'bk_description' => null,
                'bk_page' => 29,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '420',
                'bk_edition_volume' => null,
                'bk_published_year' => '2021',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Splash Smart Path to Learning English SMK/MAK Grade XII',
                'bk_description' => null,
                'bk_page' => 30,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '420',
                'bk_edition_volume' => null,
                'bk_published_year' => '2023',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Splash Smart Path to Learning English SMK/MAK Grade XII',
                'bk_description' => null,
                'bk_page' => 1,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '420',
                'bk_edition_volume' => null,
                'bk_published_year' => '2023',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Splash Smart Path to Learning English SMK/MAK Grade XI',
                'bk_description' => null,
                'bk_page' => 10,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '420',
                'bk_edition_volume' => null,
                'bk_published_year' => '2022',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Matematika SMK/MAK Kelas X',
                'bk_description' => null,
                'bk_page' => 28,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '510',
                'bk_edition_volume' => null,
                'bk_published_year' => '2021',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Matematika SMK/MAK Kelas XI',
                'bk_description' => null,
                'bk_page' => 36,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '510',
                'bk_edition_volume' => null,
                'bk_published_year' => '2021',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Matematika SMK/MAK Kelas XII',
                'bk_description' => null,
                'bk_page' => 29,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '510',
                'bk_edition_volume' => null,
                'bk_published_year' => '2022',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'PJOK (Pendidikan Jasmani, Olahraga, dan Kesehatan) SMK/MAK Kelas X',
                'bk_description' => null,
                'bk_page' => 15,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '796',
                'bk_edition_volume' => null,
                'bk_published_year' => '2022',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Sejarah SMK/MAK Kelas X',
                'bk_description' => null,
                'bk_page' => 27,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '960',
                'bk_edition_volume' => null,
                'bk_published_year' => '2021',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Proyek IPAS (Ilmu Pengetahuan Alam) SMK/MAK Kelas X',
                'bk_description' => null,
                'bk_page' => 24,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '510',
                'bk_edition_volume' => null,
                'bk_published_year' => '2021',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Nihongo de Yarou (Buku Ajar Bahasa Jepang Fase F) SMK/MAK',
                'bk_description' => null,
                'bk_page' => 14,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '496',
                'bk_edition_volume' => null,
                'bk_published_year' => '2022',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Projek Kreatif dan Kewirausahaan SMK/MAK Kelas XI',
                'bk_description' => null,
                'bk_page' => 10,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2023',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Projek Kreatif dan Kewirausahaan SMK/MAK Kelas XII',
                'bk_description' => null,
                'bk_page' => 10,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2023',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Informatika SMK/MAK Kelas X',
                'bk_description' => null,
                'bk_page' => 30,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '4',
                'bk_edition_volume' => null,
                'bk_published_year' => '2021',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Basis Data SMK/MAK Kelas XI',
                'bk_description' => null,
                'bk_page' => 13,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '1',
                'bk_edition_volume' => null,
                'bk_published_year' => '2024',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Dasar-dasar Pengembangan Perangkat Lunak dan Gim SMK/MAK Kelas X Fase E Volume 1',
                'bk_description' => null,
                'bk_page' => 31,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2022',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Dasar-dasar Pengembangan Perangkat Lunak dan Gim SMK/MAK Kelas X Fase E Volume 2',
                'bk_description' => null,
                'bk_page' => 15,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2022',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Pemrograman Web SMK/MAK Kelas XI',
                'bk_description' => null,
                'bk_page' => 15,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2024',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Karya Desain SMK/MAK Kelas XI Fase F',
                'bk_description' => null,
                'bk_page' => 15,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '745',
                'bk_edition_volume' => null,
                'bk_published_year' => '2023',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Dasar-dasar Desain Komunikasi Visual SMK/MAK Kelas X Fase E Volume 1',
                'bk_description' => null,
                'bk_page' => 19,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '700',
                'bk_edition_volume' => null,
                'bk_published_year' => '2023',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Dasar-dasar Desain Komunikasi Visual SMK/MAK Kelas X Fase E Volume 2',
                'bk_description' => null,
                'bk_page' => 17,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '700',
                'bk_edition_volume' => null,
                'bk_published_year' => '2024',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Menerapkan Desain Brief SMK/MAK Kelas XI Fase F',
                'bk_description' => null,
                'bk_page' => 15,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2024',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Bupena Merdeka Sejarah SMK/MAK Kelas XI',
                'bk_description' => null,
                'bk_page' => 1,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '960',
                'bk_edition_volume' => null,
                'bk_published_year' => '2024',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Bupena Merdeka Matematika SMK/MAK Kelas XII',
                'bk_description' => null,
                'bk_page' => 1,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '510',
                'bk_edition_volume' => null,
                'bk_published_year' => '2023',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Dasar-dasar Teknik Mesin Fase E SMK/MAK Kelas X Volume 1',
                'bk_description' => null,
                'bk_page' => 1,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '621',
                'bk_edition_volume' => null,
                'bk_published_year' => '2022',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Dasar-dasar Teknik Mesin Fase E SMK/MAK Kelas X Volume 2',
                'bk_description' => null,
                'bk_page' => 1,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '621',
                'bk_edition_volume' => null,
                'bk_published_year' => '2023',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Pemasangan dan Konfigurasi Perangkat Jaringan Fase F SMK/MAK Kelas XI Volume 1',
                'bk_description' => null,
                'bk_page' => 1,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2023',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Pemasangan dan Konfigurasi Perangkat Jaringan Fase F SMK/MAK Kelas XI Volume 2',
                'bk_description' => null,
                'bk_page' => 1,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2023',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Keamanan Jaringan Fase F SMK/MAK Kelas XI Volume 1',
                'bk_description' => null,
                'bk_page' => 1,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2023',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Panggelar Basa Sunda Pikeun SMA/MA/SMK/MAK Kelas X',
                'bk_description' => null,
                'bk_page' => 2,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '499',
                'bk_edition_volume' => null,
                'bk_published_year' => '2023',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Panduan Antibullying untuk Siswa',
                'bk_description' => null,
                'bk_page' => 3,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '303',
                'bk_edition_volume' => null,
                'bk_published_year' => '2022',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Desain Interaksi: Fundamental dan Proses',
                'bk_description' => null,
                'bk_page' => 3,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '745',
                'bk_edition_volume' => null,
                'bk_published_year' => '2022',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Pendidikan Pancasila SMK/MAK Kelas X',
                'bk_description' => null,
                'bk_page' => 20,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '323',
                'bk_edition_volume' => null,
                'bk_published_year' => '2025',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Pendidikan Pancasila SMK/MAK Kelas XI',
                'bk_description' => null,
                'bk_page' => 20,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '323',
                'bk_edition_volume' => null,
                'bk_published_year' => '2025',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Basis Data SMK/MAK Kelas XI KK Rekayasa Perangkat Lunak',
                'bk_description' => null,
                'bk_page' => 20,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '1',
                'bk_edition_volume' => null,
                'bk_published_year' => '2024',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Projek Kreatif dan Kewirausahaan SMK/MAK Kelas XI KK Teknologi Informasi',
                'bk_description' => null,
                'bk_page' => 30,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2024',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'PJOK (Pendidikan Jasmani, Olahraga, dan Kesehatan) SMK/MAK Kelas X',
                'bk_description' => null,
                'bk_page' => 20,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '796',
                'bk_edition_volume' => null,
                'bk_published_year' => '2025',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Menerapkan Desain Brief SMK/MAK Kelas XI Fase F KK Desain Komunikasi Visual',
                'bk_description' => null,
                'bk_page' => 15,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2024',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Pemrograman Web SMK/MAK Kelas XI KK Rekayasa Perangkat Lunak',
                'bk_description' => null,
                'bk_page' => 20,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2024',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Projek Kreatif dan Kewirausahaan SMK/MAK Kelas XII Bidang Keahlian Teknologi Informasi',
                'bk_description' => null,
                'bk_page' => 30,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2024',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Dasar-dasar Pengembangan Perangkat Lunak dan Gim Fase E Vol.1 PK PPLG SMK/MAK Kelas X',
                'bk_description' => null,
                'bk_page' => 20,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2023',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
            [
                'bk_isbn' => null,
                'bk_title' => 'Dasar-dasar Pengembangan Perangkat Lunak dan Gim Fase E Vol.2 PK PPLG SMK/MAK Kelas X',
                'bk_description' => null,
                'bk_page' => 20,
                'bk_img_url' => null,
                'bk_img_public_id' => null,
                'bk_type' => '1',
                'bk_permission' => '1',
                'bk_file_url' => null,
                'bk_file_public_id' => null,
                'bk_unit_price' => '5',
                'bk_edition_volume' => null,
                'bk_published_year' => '2024',
                'bk_publisher_id' => $pub->pub_id ?? null,
                'bk_major_id' => $mjr->bk_mjr_id ?? null,
                'bk_origin_id' => $orgn->bk_orgn_id ?? null,
                'bk_created_at' => $now,
                'bk_updated_at' => $now,
                'bk_sys_note' => 'Manual seed'
            ],
        ]);
    }
}
